const {
  PROJECT_ID,
  API_KEY,
  DATABSE_ID,
  PATIENTS_COLLECTION_ID,
  TRAINER_COLLECTION_ID,
  APPOINTMENT_COLLECTION_ID,
  NEXT_PUBLIC_BUCKET_ID: BUCKET_ID,
  NEXT_PUBLIC_ENDPOINT: ENDPOINT
} = process.env;
